# Generated by Django 2.1.5 on 2019-03-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='allowed_membership',
            new_name='allowed_memberships',
        ),
    ]
